---
pagetitle: "Home"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Please explore the interactive ecosystem for Channel Islands National Marine Sanctuary. Navigate by clicking on icons representing major habitats, species of interest, major climate and ocean drivers, and key human activities. These interactive icons and silhouettes access status and trend data, images, web stories and other supporting content.

## Test H2

Please explore the interactive ecosystem for Channel Islands National Marine Sanctuary. Navigate by clicking on icons representing major habitats, species of interest, major climate and ocean drivers, and key human activities. These interactive icons and silhouettes access status and trend data, images, web stories and other supporting content.

## Test H2

Please explore the interactive ecosystem for Channel Islands National Marine Sanctuary. Navigate by clicking on icons representing major habitats, species of interest, major climate and ocean drivers, and key human activities. These interactive icons and silhouettes access status and trend data, images, web stories and other supporting content.

## Test H2

Please explore the interactive ecosystem for Channel Islands National Marine Sanctuary. Navigate by clicking on icons representing major habitats, species of interest, major climate and ocean drivers, and key human activities. These interactive icons and silhouettes access status and trend data, images, web stories and other supporting content.

## Test H2

Please explore the interactive ecosystem for Channel Islands National Marine Sanctuary. Navigate by clicking on icons representing major habitats, species of interest, major climate and ocean drivers, and key human activities. These interactive icons and silhouettes access status and trend data, images, web stories and other supporting content.

## Test H2

Please explore the interactive ecosystem for Channel Islands National Marine Sanctuary. Navigate by clicking on icons representing major habitats, species of interest, major climate and ocean drivers, and key human activities. These interactive icons and silhouettes access status and trend data, images, web stories and other supporting content.


